/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useFrame } from '@react-three/fiber';
import { useGLTF } from '@react-three/drei';

function Estrella(props) {
  const ref = useRef();
  useFrame(() => (ref.current.rotation.y += 0.01));

  const { nodes } = useGLTF('/Pico.glb');
  return (
    <group ref={ref} {...props} dispose={null}>
      <mesh
        geometry={nodes.Sphere.geometry}
        material={nodes.Sphere.material}
        position={[1, 1, 1]}
      >
        <meshPhongMaterial color="orange" specular={'yellow'} />
      </mesh>
    </group>
  );
}

useGLTF.preload('/Pico.glb');

export default Estrella;
